### ISSUE TITLE
Program not found

### ISSUE THREAD

**Issue by anglaborg** [primaeval/plugin.video.iptv.recorder#18]
Hello,

When i press button "IPTV Recorder" in the Program info menu i get an error saying

> IPTV Recorder
> program not found

Does anyone know what the problem is?

Thank you!

**Comment by anglaborg** [comment]
Thank you for fast answer!

I currently having "IPTV Simple Client" in both xmltv and m3u. Everything with Simple Client is working fine. 
Should this work? Mayby I could try to set the xmltv and m3u links manually. I will try the test files also.

**Comment by anglaborg** [comment]
Still not working with test files.

**Comment by primaeval** [comment]
If it didn't work with the test files there is a bigger problem.

Did they load up in both addons and
could you play the test channel in both addons and see the test program?

There is a setting for "Settings\Debug\extra menus" that brings up a "Maintenance\NUKE" command that will clear your settings and force a reload without having to restart Kodi and wait.

**Comment by anglaborg** [comment]
With booth addons; do you mean IPTV Simple Client and IPTV Recorder?

**Comment by primaeval** [comment]
Yes

**Comment by anglaborg** [comment]
Loaded up the tests for both addons and know there is no error. Get the options Record once, daily and so on.....

**Comment by primaeval** [comment]
So you can get to the Record options from Kodi \ TV \ Channels \ Guide \ Program Information \ IPTV Recorder ?

**Comment by anglaborg** [comment]
Yes, correct.

**Comment by primaeval** [comment]
Then the problem is something missing from your xmltv / m3u combination. Usually it is something like a missing tvg-id attribute. Post a channel EXTINF line from your m3u that doesn't work and the corresponding channel from the top of your xmltv file.

**Comment by anglaborg** [comment]
Im using a URL for both my m3u and xmltv, does that matter?

**Comment by primaeval** [comment]
It doesn't matter to the addon but I need to see what is missing. So you need to download them first or open them in a browser so you can paste the info here.

**Comment by anglaborg** [comment]
This is the "m3u with options", dont really know the difference. 
```
#EXTINF:-1 tvg-id="SVT1.se" tvg-name="SVT1 SE" tvg-logo="https://cdn-static.ams3.cdn.digitaloceanspaces.com/picons/svt1.png" group-title="LIVE: Sweden",SVT1 SE
http://******.m3u8
```

The EPG-link gives me HTTP Error 401 so im not able to download that. The EPG in Guide works tho?
 Do you know any other way I can collect the info from?

**Comment by primaeval** [comment]
If it loaded in IPTV Recorder there should be a copy of the xml as "userdata\addon_data\plugin.video.iptv.recorder\xmltv1.xml"

**Comment by primaeval** [comment]
The m3u is "userdata\addon_data\plugin.video.iptv.recorder\channels1.m3u"

**Comment by anglaborg** [comment]
channels1.m3u

```
#EXTINF:-1 tvg-id="SVT1.se" tvg-name="SVT1 SE" tvg-logo="https://cdn-static.ams3.cdn.digitaloceanspaces.com/picons/svt1.png" group-title="LIVE: Sweden",SVT1 SE
http://***.m3u8

```

xmltv1.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv source-info-name="test" generator-info-name="test" generator-info-url="test">
  <channel id="test id ▒^|">
    <display-name>[B]test name ▒^|[/B]</display-name>
  </channel>
  <programme channel="test id ▒^|" start="20190224063000 +0000" stop="20200224120000 +0000">
    <title lang="en">[B]test title ▒^|[/B]</title>
    <desc lang="en">[B]test description ▒^|[/B]</desc>
    <episode-num system="xmltv_ns">1.1</episode-num>
  </programme>
</tv>
```

Can I remove settings.xml to reset settings? Seems to be using the test files even though "External xml/m3u" in Settings is set to "IPTV Simple Client"

**Comment by anglaborg** [comment]
Where is the log file located? Reinstalled the plugin but now I get "check log...." error after reboot.

**Comment by primaeval** [comment]
You could rename or delete the folder to reset everything. userdata\addon_data\plugin.video.iptv.recorder

As the xml didn't get updated and you got a 401 Unauthorized code earlier I expect you need something extra in the xml url, like a username and password.

**Comment by anglaborg** [comment]
Im using username and password in the url

**Comment by primaeval** [comment]
It must be wrong if it won't download.

kodi.log might be at the top of userdata or in temp or cache.

**Comment by primaeval** [comment]
Look in the IPTV Simple Client settings file to make sure you have got the correct epgUrl.
"userdata\addon_data\pvr.iptvsimple\settings.xml"

**Comment by anglaborg** [comment]
This is the log
https://pastebin.com/MPXQquYq

EPG and Channels are working in the Simple Client.
It is the same url's in 
"userdata\addon_data\pvr.iptvsimple\settings.xml" 
as in the 
"userdata\addon_data\plugin.video.iptv.recorder\settings.xml"

**Comment by anglaborg** [comment]
Might have found the problem...
My url contains a "&" which have set my URL for both xml and m3u in the Simple Client's settings.xml to http://*******?username***** **& amp;** password........." 

Trying without the "&amp;"

**Comment by anglaborg** [comment]
Did not work, still error when starting the plugin
https://pastebin.com/dhMkHdGg

**Comment by primaeval** [comment]
Your xml loaded up ok for me in Windows in both addons. Be careful what you paste on pastebin. It is public.
So it looks like it is a pi problem. Your xml file is huge. I wouldn't be surprised if the pi is running out of memory. When python loads it it takes up a lot of memory. 
Try it on a Windows or another desktop computer with lots of memory and see what I mean.

**Comment by anglaborg** [comment]
Thank you for notifying me about the pastebin, have done a reset of my credentials.

Do you think a scheduled wget everyday of the file might work? And then point the recorder to that file?

**Comment by primaeval** [comment]
I just think it's too big for python on the pi. Python uses a lot of memory to do the same things that a c addon does. See if there is a cutdown version of the xmltv file available. You could see if my "xmltv Meld" addon can reduce the size of it by selecting only the channels you need.

But first make sure there is not something else wrong by loading it up in Windows or another desktop/laptop operating system.

**Comment by anglaborg** [comment]
Now Im using a xmltv for only my country. 
No error at startup but still "IPTV Recorder program not found"

I guess its because the channel id is not the same?

xmltv1.xml
`  <channel id="svt1.svt.se">
    <display-name lang="en">SVT1</display-name>
    <base-url>https://xmltv.xmltv.se/</base-url>
    <icon src="http://chanlogos.xmltv.se/svt1.svt.se.png"/>
  </channel>
`

m3u
```
#EXTINF:-1 tvg-id="SVT1.se" tvg-name="SVT1 SE" tvg-logo="https://cdn-static.ams3.cdn.digitaloceanspaces.com/picons/svt1.png" group-title="LIVE: Sweden",SVT1 SE
```

**Comment by primaeval** [comment]
The id has to be the same exactly including case I think.
It's probably easier for you to change the m3u rather than the xmltv. So make the m3u:

```
#EXTINF:-1 tvg-id="svt1.svt.se" tvg-name="SVT1 SE" tvg-logo="https://cdn-static.ams3.cdn.digitaloceanspaces.com/picons/svt1.png" group-title="LIVE: Sweden",SVT1 SE
```

**Comment by marcwlux** [comment]
I have the same issue 'Program not found', I think it's related that the recorder is crashing when initialising.
I get the following error in my logs:
2019-06-15 13:00:12.689 T:6124 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
2019-06-15 13:00:13.072 T:6124  NOTICE: [xbmcswift2] Request for "/renew_jobs" matches rule for function "renew_jobs"
2019-06-15 13:02:10.516 T:7236 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
2019-06-15 13:02:10.695 T:7236  NOTICE: [xbmcswift2] Request for "/full_service" matches rule for function "full_service"
2019-06-15 13:02:10.704 T:968   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.recordlabels.white/
2019-06-15 13:02:10.923 T:7236 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
2019-06-15 13:02:12.213 T:7236   ERROR: {'confidence': 0.99, 'language': '', 'encoding': 'utf-8'}
2019-06-15 13:02:12.213 T:7236 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
2019-06-15 13:02:17.837 T:7236 WARNING: Previous line repeats 636 times.
2019-06-15 13:02:17.837 T:7236   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "C:\Users\wamal\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3484, in <module>
                                                plugin.run()
                                              File "C:\Users\wamal\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\wamal\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\wamal\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 2494, in full_service
                                                xmltv()
                                              File "C:\Users\wamal\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3102, in xmltv
                                                S = int(S if S else 0) + 1
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--

there seems to be type error. I'm using 18.2 on WIN10, Simple PVR Client, and Catch-Up TV and More.
My m3u is original from Catch-Up. They are hosted in the net. (local is the same)
