### ISSUE TITLE
V19 update? Python 3 compatibility.

### ISSUE THREAD

**Issue by Yellowsub2** [primaeval/plugin.video.iptv.recorder#33]
Hi thanks for the great work for this addon. Will this addon be updated for V19? Python 3? I am getting errors with import ctypes _init_.py cannot import name union from line 8. i am running Windows10 and Kodi V19. I've managed to get a couple of other addons working for Py3 but I'm a noob and this is beyond my current knowledge.   Error Contents: cannot import name 'Union' from 'ctypes' (C:\Program Files\Kodi\system\python\Lib\ctypes\__init__.py)                                            Traceback (most recent call last):     File "C:\Users\All\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 10, in <module>    import ctypes
File "C:\Program Files\Kodi\system\python\Lib\ctypes\__init__.py", line 8, in <module> from ctypes import Union, Structure, Array       ImportError: cannot import name 'Union' from 'ctypes' (C:\Program Files\Kodi\system\python\Lib\ctypes\__init__.py)

**Comment by Dobi-Dev** [comment]
I have worked a bit on the compatibility and ask a pull request : https://github.com/primaeval/plugin.video.iptv.recorder/pull/39

I have not tested it on Matrix, so I am not sure that your problem is really solved (and there may be some other issues).
Edit : I have tested it and yes, there is errors so it won't be ok with juste these changes.

**Comment by helio58** [comment]
Hi, any news with the python 3 in kodi matrix?
Thanks

**Comment by Dobi-Dev** [comment]
The initial author of this plugin seems inactive. Even if I am not working on it at this time, I have forked his repo and updated it to support kodi matrix : https://github.com/Dobi-Dev/plugin.video.iptv.recorder

**Comment by helio58** [comment]
Thanks Dobi-Dev,
I have download your plugin but unable to install. Got a wrong structure error 
I m running kodi 19.0-Alpha1 (18.9.701) on macbook
I m not a developer just a user, is there a walk around this? 
Thanks

**Comment by Dobi-Dev** [comment]
I will check that tonight if I can.

**Comment by helio58** [comment]
Thank you. In witch platform are you using iptv recorder? and kodi version?

**Comment by Dobi-Dev** [comment]
I was on windows. I can't tell you which kodi version since I havec uninstalled it since. I will try on the latest version.

**Comment by Dobi-Dev** [comment]
Can you try to download again the following zip file : https://github.com/Dobi-Dev/plugin.video.iptv.recorder/releases/download/v0.2.0/plugin.video.iptv.recorder-matrix.zip and install it ?

**Comment by helio58** [comment]
@Dobi-Dev , YES its working. I personally like this add-on very much.
Thank you for taking your time. Thank you.

**Comment by Ramboxman** [comment]
This is working on Matrix, but is missing the skin Estuary for IPTV recorder.  Any why to add the skin? Running in POP OS Linux

**Comment by Dobi-Dev** [comment]
I have removed it since I was not using it and I didn't know what feature it brings.
At this time, I can't try to add it again since I am not at home due to covid ...
