### ISSUE TITLE
Kodi 19 : installation issue

### ISSUE THREAD

**Issue by adyb0** [primaeval/plugin.video.iptv.recorder#49]
Hello,

This plugin cant be installed on kodi  19.
I seems that python 3 upgrade can be the problèm.

Regards

**Comment by tbrek** [comment]
You can fix depedencies yourself:

`  <requires>
    <import addon="xbmc.python" version="3.0.0" />
    <import addon="script.module.xbmcswift2"/>
    <import addon="script.module.requests"/>
    <import addon="script.module.chardet" />
    <import addon="script.module.pytz" />
    <import addon="script.module.dateutil" />
    <import addon="script.module.kodi-six" />
  </requires>`

**Comment by adyb0** [comment]
No i'm not able to fix it by myself. I already try this in addon.xml
`<import addon="xbmc.python" version="3.0.0" /> `
```

2021-03-06 19:28:13.239 T:15012    INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2021-03-06 19:28:15.040 T:21344    INFO <general>: initializing python engine.
2021-03-06 19:28:15.088 T:21344   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "........\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\context.py", line 12, in <module>
                                                       channel = channel.decode("utf8")
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
                                                   
2021-03-06 19:28:15.093 T:21344    INFO <general>: Python interpreter stopped
2021-03-06 19:29:22.683 T:15012    INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2021-03-06 19:29:22.730 T:17632    INFO <general>: initializing python engine.
2021-03-06 19:29:23.099 T:17632   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'HTMLParser'
                                                   Traceback (most recent call last):
                                                     File "........\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3, in <module>
                                                       from HTMLParser import HTMLParser
                                                   ModuleNotFoundError: No module named 'HTMLParser'
                                                   -->End of Python script error report<--
                                                   
2021-03-06 19:29:23.109 T:17632    INFO <general>: Python interpreter stopped
2021-03-06 19:29:23.128 T:11952   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.iptv.recorder/
2021-03-06 19:29:23.140 T:15012   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iptv.recorder/) failed
2021-03-06 19:29:33.241 T:15012    INFO <general>: Loading skin file: DialogMediaSource.xml, load type: KEEP_IN_MEMORY
2021-03-06 19:29:36.864 T:15012 WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
```

**Comment by tbrek** [comment]
Drop `channel = channel.decode("utf8")` from line 8. Python 3 does not need that.

**Comment by adyb0** [comment]
No, something goes Wrong.
I think i find someone With the same problem in a fork PR. https://github.com/Dobi-Dev/plugin.video.iptv.recorder/pull/1/commits/fd4e0a00c5b82bf12f8395a86e17d1153ee04a26

**Comment by tbrek** [comment]
> No, something goes Wrong.
> I think i find someone With the same problem in a fork PR. [Dobi-Dev@fd4e0a0](https://github.com/Dobi-Dev/plugin.video.iptv.recorder/commit/fd4e0a00c5b82bf12f8395a86e17d1153ee04a26)

Here's my fixed fork https://github.com/tbrek/plugin.video.iptv.recorder/tree/matrix for 19.0

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/9820995/110249781-b9309b80-7f6f-11eb-8809-37a57ab2e484.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/9820995/110249784-bfbf1300-7f6f-11eb-92ee-d4c78fca9b53.png">

**Comment by adyb0** [comment]
I will try if one off them work.
https://github.com/tbrek/plugin.video.iptv.recorder/tree/matrix
https://github.com/Dobi-Dev/plugin.video.iptv.recorder (with or without pr https://github.com/Dobi-Dev/plugin.video.iptv.recorder/pull/1)
https://github.com/Publish3r/repository.kodi.matrix/tree/main/plugin.video.iptv.recorder

Maybe xmltv format change something. I dont know.

**Comment by tbrek** [comment]
> I will try if one off them work.
> https://github.com/tbrek/plugin.video.iptv.recorder/tree/matrix

This is one is mine and it works. I have just tried. Showing list of programs and records with no issues.

**Comment by adyb0** [comment]
nothing realy work.
Thanks. I will find another solution for the moment. Maybe with streamlink or something like that. 

I think it yours are the closest to the goal but not. I had file with no data inside. In case you wanted logs : 
By EPG guide : 
```
22:36:44.306 T:12612    INFO <general>: CPythonInvoker(10, ....AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script successfully run
2021-03-07 22:36:50.428 T:8660  WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2021-03-07 22:36:57.805 T:8660     INFO <general>: Skipped 5 duplicate messages..
2021-03-07 22:36:57.805 T:8660     INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2021-03-07 22:37:07.187 T:8660  WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2021-03-07 22:37:18.853 T:8660  WARNING <general>: Skipped 3 duplicate messages..
2021-03-07 22:37:18.853 T:8660  WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2021-03-07 22:37:32.554 T:6664     INFO <general>: Skipped 9 duplicate messages..
2021-03-07 22:37:32.554 T:6664     INFO <general>: initializing python engine.
2021-03-07 22:37:32.669 T:6664     INFO <general>: CPythonInvoker(11, .....AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\contextEPG.py): script successfully run
2021-03-07 22:37:32.673 T:8784     INFO <general>: initializing python engine.
2021-03-07 22:37:32.692 T:6664     INFO <general>: Python interpreter stopped
2021-03-07 22:37:33.303 T:8784     INFO <general>: [xbmcswift2] Request for "/record_epg/36 Chanel Name/name/2021-03-07 20:40:00/2021-03-07 22:45:00" matches rule for function "record_epg"
2021-03-07 22:37:33.304 T:22388 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-07 22:37:33.304 T:8784     INFO <general>: CPythonInvoker(12, ....AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-07 22:37:33.304 T:8784     INFO <general>: CPythonInvoker(12, ....\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): waiting on thread 22388
2021-03-07 22:37:33.305 T:22388 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-07 22:37:33.329 T:22388   ERROR <general>: Skipped 1 duplicate messages..
2021-03-07 22:37:33.329 T:22388   ERROR <general>: "UUID: <module 'uuid' from 'x:\\\\Program Files\\\\Kodi\\\\system\\\\python\\\\Lib\\\\uuid.py'>, Channelid: None, Channel Name: CHANEL_NAME, Title: Name, Start: 2021-03-07 19:40:00, Stop: 2021-03-07 21:45:00, Type: RECORD"
2021-03-07 22:37:33.337 T:6636     INFO <general>: initializing python engine.
2021-03-07 22:37:33.356 T:6636  WARNING <general>: CPythonInvoker(13): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
2021-03-07 22:37:33.498 T:8784     INFO <general>: Python interpreter stopped
2021-03-07 22:37:36.566 T:6636     INFO <general>: CPythonInvoker(13, special://profile/addon_data/plugin.video.iptv.recorder/jobs/5384fba6-7f8d-11eb-9496-4ccc6a7eefaf.py): script successfully run
2021-03-07 22:37:36.618 T:6636     INFO <general>: Python interpreter stopped
2021-03-07 22:37:55.083 T:8660    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-03-07 22:37:55.108 T:1712     INFO <general>: initializing python engine.
2021-03-07 22:37:55.691 T:1712     INFO <general>: [xbmcswift2] Request for "/" matches rule for function "index"
2021-03-07 22:37:55.691 T:1712  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-07 22:37:55.706 T:1712     INFO <general>: CPythonInvoker(14, ....\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-07 22:37:55.765 T:1712     INFO <general>: Python interpreter stopped
2021-03-07 22:37:59.324 T:4896     INFO <general>: initializing python engine.
2021-03-07 22:37:59.931 T:4896     INFO <general>: [xbmcswift2] Request for "/recordings" matches rule for function "recordings"
2021-03-07 22:37:59.932 T:4896  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-07 22:37:59.938 T:4896     INFO <general>: Skipped 12 duplicate messages..
2021-03-07 22:37:59.938 T:4896     INFO <general>: CPythonInvoker(15, ......\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-07 22:37:59.995 T:4896     INFO <general>: Python interpreter stopped
```

By chanel 
```
1-03-07 22:45:07.246 T:20064   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "....\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\context.py", line 13, in <module>
                                                       channel = channel.decode("utf8")
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--
```

**Comment by tbrek** [comment]
Can you post part of your EPG, and part of m3u file? Make sure there's no passwords, tokens etc.

**Comment by adyb0** [comment]
Looks like this.

```
#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="ZeeTAMILHD" tvg-logo="http://logotvdomain.com/logochanel/100.png" group-title="Hindi;Asia",Zee TAMIL HD
http://tvdomain.com/iptv/ch100?var=something&var1=something
#EXTINF:-1 tvg-id="" tvg-name="ZeeTalkiesHD" tvg-logo="http://logotvdomain.com/logochanel/101.png" group-title="Hindi;Asia",Zee Talkies HD
http://tvdomain.com/iptv/ch101?var=something&var1=something
#EXTINF:-1 tvg-id="" tvg-name="ZeeSarthak" tvg-logo="http://logotvdomain.com/logochanel/102.png" group-title="Hindi;Asia",Zee Sarthak
http://tvdomain.com/iptv/ch102?var=something&var1=something
#EXTINF:-1 tvg-id="" tvg-name="ZeeRajasthan News" tvg-logo="http://logotvdomain.com/logochanel/103.png" group-title="Hindi;Asia",Zee Rajasthan News
http://tvdomain.com/iptv/ch103?var=something&var1=something
#EXTINF:-1 tvg-id="" tvg-name="ZeePunjabi" tvg-logo="http://logotvdomain.com/logochanel/104.png" group-title="Hindi;Asia",Zee Punjabi
```




```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-url="http://epgdomain.com" source-info-name="XML" generator-info-name="XML" generator-info-url="http://epgdomain.com">
  <channel id="ZeeTAMILHD">
    <display-name>ZeeTAMILHD</display-name>
    <icon src="" />
  </channel>
<channel id="ZeeTalkiesHD">
    <display-name>ZeeTalkiesHD</display-name>
    <icon src="" />
  </channel>
<channel id="ZeeSarthak">
    <display-name>ZeeSarthak</display-name>
    <icon src="" />
  </channel>
<channel id="ZeeRajasthan">
    <display-name>ZeeRajasthan</display-name>
    <icon src="" />
  </channel>
<channel id="ZeePunjabi">
    <display-name>ZeePunjabi</display-name>
    <icon src="" />
  </channel>
<programme start="20210227070000 +0100" stop="20210227073000 +0500" channel="ZeeTAMILHD">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<desc lang="en">no description</desc>
	<category lang="en">unknown</category>
	<icon src="https://imgdomain.com/image-api/v1/image/40f2b20d0774012aada772d6" />
</programme>
<programme start="20210304224200 +0500" stop="20210305001900 +0500" channel="ZeeTAMILHD">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<desc lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</desc>
	<category lang="en">Movie</category>
	<category lang="en">Suspense</category>
	<icon src="https://imgdomain.com/image/2286556.jpg" />
	<rating system="smthg">
      <value>-10</value>
	</rating>
</programme>
<programme start="20210227073000 +0100" stop="20210227081500 +0500" channel="ZeeTalkiesHD">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<desc lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</desc>
	<category lang="en">unknown</category>
	<icon src="https://imgdomain.com/image-api/v1/image/c603e811333bf324fd441a" />
</programme>
<programme start="20210227081500 +0100" stop="20210227090000 +0500" channel="ZeeSarthak">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<desc lang="en">no description</desc>
	<category lang="en">unknown</category>
	<icon src="https://imgdomain.com/image-api/v1/image/cf4047cb55ed31cca92266e4" />
</programme>
<programme start="20210227090000 +0100" stop="20210227094500 +0500" channel="ZeeSarthak">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<desc lang="en">no description</desc>
	<category lang="en">unknown</category>
	<icon src="https://imgdomain.com/image-api/v1/image/5b15d012f89dda856a939c11" />
</programme>
<programme start="20210315110000 -0500" stop="20210315120000 -0500" channel="unknown">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<desc lang="en">no description</desc>
	<category lang="en">unknown</category>
</programme>
<programme start="20210305060500 +0500" stop="20210305074500 +0500" channel="ZeePunjabi">
	<title lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</title>
	<sub-title lang="en">abcd</sub-title>
	<episode-num system="xmltv_ns">6.1.</episode-num>
	<desc lang="en">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzàùîïôöéèêë",-;. /!?,':</desc>
	<category lang="en">Serie</category>
	<category lang="en">sfi</category>
	<icon src="https://imgdomain.com/image/2236556.jpg" />
	<rating system="MPAA">
      <value>PG</value>
    </rating>
</programme>
</tv>
```

**Comment by tbrek** [comment]
Updated my fork. Feel free to try again.

**Comment by adyb0** [comment]
😫

```
2021-03-09 22:52:55.391 T:6880 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'TypeError'>
Error Contents: decode() argument 'encoding' must be str, not None
Traceback (most recent call last):
File "....\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3455, in <module>
plugin.run()
File "....\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 338, in run
items = self._dispatch(self.request.path)
File "....\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 312, in _dispatch
listitems = view_func(**items)
File "....\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 2529, in full_service
xmltv()
File "....\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 2963, in xmltv
data = data_bytes.decode(encoding)
TypeError: decode() argument 'encoding' must be str, not None
-->End of Python script error report<-- 
```

**Comment by tbrek** [comment]
@adrien-ber can we move that discussion into my fork please? It will be much easier for me to track it down.

**Comment by tbrek** [comment]
BTW. Updated my fork, feel free to try again.

**Comment by gsantner** [comment]
So...I reached here from [kodinerds](https://forum.kodi.tv/showthread.php?tid=329991) just to see this project is dead once again (such a project has been there literally with every kodi version as far I get it). By reading through this discussion I got that tbrek has created a working fork. Just saw it's [dropped](https://github.com/tbrek/plugin.video.iptv.recorder/issues/7) shortly after.

Is there any remotely longterm solution available for kodi (& iptv simple tv) that NOT breaks in a matter of a few weeks? It can't be that hard to write code that survives at least a year... After all it boils down to a start & end date, timer/cronjob and ffmepg commandline call, correct? 

Is there somebody interested in working on (& MAINTAINING) a more stable, but minimal solution (i.e. minimal features, less reasons to break)?

**Comment by oatmealm** [comment]
@tbrek  hi. wondering what is the status of this plugin? Is you fork the way to go?

**Comment by tbrek** [comment]
> @tbrek hi. wondering what is the status of this plugin? Is you fork the way to go?

The fork should stil work in 19.x. It's no longer maintained though. It was dropped and replaced by https://github.com/tbrek/tbrek-kodi-repo

**Comment by ermete74** [comment]
Hello tbrek.
Excuse me for my bad english.
I am using Kodi 19.5 Matrix x64 on PC with Windows 10 22H2.
I tried using the plugin.video.iptv.recorder add-on
downloaded from this link
https://github.com/tbrek/plugin.video.iptv.recorder/tree/matrix
Does not work.
I used your IPTV Archive Downloader addon downloaded from this link
https://github.com/tbrek/tbrek-kodi-repo
Does not work.
Two different errors are noted in the kodi.log file.
I would like to talk to you and fix the error.
Where can we talk?
Thank you.

**Comment by tbrek** [comment]
> https://github.com/tbrek/tbrek-kodi-repo

Submit an issue here https://github.com/tbrek/tbrek-kodi-repo

So I can have a look.
